# Generated by Django 4.2.5 on 2023-09-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_solid',
            new_name='is_sold',
        ),
    ]
